name: Update Train Data

on:
  schedule:
    # This runs at 04:00 AM UTC every day
    - cron: '0 4 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trains.json
          git commit -m "Auto-update train data" || exit 0
          git push
